#goal
float64   turnAngle 
float64[] pX
float64[] pY
float64[] pZ
---
#result
float64   turnAngle 
float64[] pX
float64[] pY
float64[] pZ
---
#feedback
float64   turnAngle 
float64[] pX
float64[] pY
float64[] pZ
